### ISSUE TITLE
Cannot compile or build

### ISSUE THREAD

**Issue by Gnol-VN** [layeredqueuing/V5#1]
Dear authors,
Can you please specify the GCC version, G++ version, and Ubuntu version used to make the project?
I cannot make it with GCC 7.4.0.
Otherwise, can you provide us with a compiled application?
Thank you a lot, and wish you to have a nice day !!

**Comment by layeredqueuing** [comment]
Likely because the configure script is missing.  
Run:
 ./.bootstrap
 ./configure
 
Bootstrap will do the aclocal, automake, autoconfig stuff.  I'll 'push' in the configure scripts though.
