### ISSUE TITLE
Installation instructions seem outdated

### ISSUE THREAD

**Issue by cbkurz** [layeredqueuing/V5#3]
Hi,

following the installation instructions of the README-LOCAL on the path with MinGW2 there are instructions under 3) that state to install some texlive packages to create the documentation. However, when trying to install the packages (with all of them), MinGW states the error that the target is not found.

Commands in Question:
```
3) The user manuals are built using LaTeX.
   Install texlive
  503  pacman -S mingw-w64-i686-texlive-recommended
  504  pacman -S mingw-w64-i686-texlive-core
  505  pacman -S mingw-w64-i686-texlive-latex-extra
  510  pacman -S mingw-w64-i686-texlive-font-utils
  522  pacman -S mingw-w64-i686-texlive-plain-generic
```

Error:
```
$ pacman -S mingw-w64-i686-texlive-core
error: target not found: mingw-w64-i686-texlive-core
```
When looking up the package, it is stated that it does not exist:
https://packages.msys2.org/package/mingw-w64-i686-texlive-core

Futhermore, I did skip that step since it seems to be optional and tried to continue with "4) Build away ..." this also run into some problems the `./configure` was not created. I also tried to run `automake` and `autoconf`, thereafter the `./configure` files was created but so severely damaged that it would not run.

Also sorry if I did something wrong, its my first time that I'm in contact with building c++ tools. Could you also reference the "README-LOCAL" file in the README.

Best regards

**Comment by cbkurz** [comment]
However when using the .tar.gz archives from the distribution repository I am able to run the scripts as described in the installation instructions. 

The problem with the missing pdf files then come into play since the NSIS Installer cannot find the `doc/tutorial/tutorial.pdf` and `doc/userman/userman.pdf`. Somehow the `dist/license.txt` is also missing.

**Comment by cbkurz** [comment]
Probably not related but I get a funny comment that states (when running from Powershell or cmd on Windows 11):
```
PS ~> lqns
lqns.exe: Input from terminal is not allowed.
```
That is the main way I want to use this program. 
Executing the `lqns.exe` from the explorer only shows a windows briefly which immediately vanishes again.

**Comment by layeredqueuing** [comment]
That one is easy.  The program expects input from standard input so that it can be used in a pipeline.  ie  “something | lqns”, or “lqns < filename.xml”.  Usually, just use “lqns filename.xml”.  

Gregory Franks, Ph.D. P.Eng
Associate Chair - Undergraduate Studies
Department of Systems and Computer Engineering
Carleton University

**Comment by layeredqueuing** [comment]
Try https://packages.msys2.org/groups/mingw-w64-x86_64-texlive-full.  However, texlive-core should be there too:  https://packages.msys2.org/package/mingw-w64-x86_64-texlive-core.  Unfortunately, I use MikTeX on the machine I'm on right now, so I will have to check the install on my other machine later this week.  

You don't need LaTeX to build the code (just the documentation).   I'll look into nsis.  I guess I never figured on someone actually trying to build an installer.  If you have installed mingw, then you run lqns from the mingw shell directly.  Prebuilt binaries for windows also exist at https://www.sce.carleton.ca/rads/lqns/LQNSdownload/  which include all the PDF documentation.

**Comment by cbkurz** [comment]
Hi, thanks a lot for the quick response.

I am perfectly fine with using the pre-build packages. Thanks for the information on them. They, however, were only accessible after I used a VPN which is located in Canada (even a site that checks if a page is up told me it is not reachable :O )
I will use the provided installer. Sorry for misinterpreting `lqns.exe: Input from terminal is not allowed.`.

lqns seems to work now, but I ran into the next problem: the solver did not write its complete solution or, more precisely, only did write a broken XML-File. I associate something like that in Java with not correctly flushing/closing my stream. Have you ever encountered something like that? Is this something I can ask here, or do you prefer another channel/new ticket?

The call I made is: `lqns -P cycles=yes \sample.xml`

Verbose Output:
```
Load: .\sample.xml...
Prepare: ...
Create: batched layers...
Check...
Initialize...
Generate...
Solve...
Iteration: 1 .... [1.87996]
Iteration: 2 .... [0.360162]
Iteration: 3 .... [0.0014047]
Iteration: 4 .... [0.000331753]
Iteration: 5 .... [3.31753e-05]
Iteration: 6 .... [3.31753e-06]
```
The sample.xml is from another project which already did use the lqns successfully.

**Comment by layeredqueuing** [comment]
I've updated the README-LOCAL file after running the whole process on a brand new windows-11 machine with the latest mingw stuff.  texlive doesn't seem to exist for i686 anymore, but that's no big deal; the 64-bit version is fine.  The executables end up in /mingw64/bin, so that will have to be added to PATH in ~/.bashrc.  The lqsim program has to run in 32-bit mode due to an ancient threading package used by the simulator, which is why mingw32 is used.

Output from sample.xml should be in sample.lqxo.  If not, please email sample.xml to greg@sce.carleton.ca.
